# 사용할 베이스 이미지를 선택합니다. 여기서는 Ubuntu 기반의 이미지를 사용합니다.
FROM ubuntu:22.04

# 환경 변수 설정
ENV DEBIAN_FRONTEND=noninteractive

# 운영체제 업데이트 및 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# 파이썬 패키지 업그레이드
RUN pip3 install --upgrade pip

# 도커 컨테이너 내에서 Python을 사용할 수 있도록 환경을 설정합니다.
ENV PATH="/usr/local/bin:${PATH}"

# 컨테이너 시작 시 파이썬 쉘을 실행
CMD ["python3"]